version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test-unit
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy
          command: echo 'deploying...'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
